import { MEDIA_AUDIO_FIELD_LABELS } from "./media-audio-field-metadata.js";
import { IRC_FIELD_LABELS } from "./schema.irc.js";

export const FIELD_LABELS: Record<string, string> = {
  meta: "元数据",
  "meta.lastTouchedVersion": "配置最后修改版本",
  "meta.lastTouchedAt": "配置最后修改时间",
  env: "环境",
  "env.shellEnv": "Shell 环境导入",
  "env.shellEnv.enabled": "启用 Shell 环境导入",
  "env.shellEnv.timeoutMs": "Shell 环境导入超时（毫秒）",
  "env.vars": "环境变量覆盖",
  wizard: "安装向导状态",
  "wizard.lastRunAt": "向导上次运行时间戳",
  "wizard.lastRunVersion": "向导上次运行版本",
  "wizard.lastRunCommit": "向导上次运行提交",
  "wizard.lastRunCommand": "向导上次运行命令",
  "wizard.lastRunMode": "向导上次运行模式",
  diagnostics: "诊断",
  "diagnostics.otel": "OpenTelemetry",
  "diagnostics.cacheTrace": "缓存追踪",
  logging: "日志",
  "logging.level": "日志级别",
  "logging.file": "日志文件路径",
  "logging.consoleLevel": "控制台日志级别",
  "logging.consoleStyle": "控制台日志样式",
  "logging.redactSensitive": "敏感数据脱敏模式",
  "logging.redactPatterns": "自定义脱敏规则",
  cli: "CLI",
  "cli.banner": "CLI Banner",
  "cli.banner.taglineMode": "CLI Banner Tagline Mode",
  update: "Updates",
  "update.channel": "Update Channel",
  "update.checkOnStart": "Update Check on Start",
  "update.auto.enabled": "Auto Update Enabled",
  "update.auto.stableDelayHours": "Auto Update Stable Delay (hours)",
  "update.auto.stableJitterHours": "Auto Update Stable Jitter (hours)",
  "update.auto.betaCheckIntervalHours": "Auto Update Beta Check Interval (hours)",
  "diagnostics.enabled": "Diagnostics Enabled",
  "diagnostics.flags": "Diagnostics Flags",
  "diagnostics.stuckSessionWarnMs": "Stuck Session Warning Threshold (ms)",
  "diagnostics.otel.enabled": "OpenTelemetry Enabled",
  "diagnostics.otel.endpoint": "OpenTelemetry Endpoint",
  "diagnostics.otel.protocol": "OpenTelemetry Protocol",
  "diagnostics.otel.headers": "OpenTelemetry Headers",
  "diagnostics.otel.serviceName": "OpenTelemetry Service Name",
  "diagnostics.otel.traces": "OpenTelemetry Traces Enabled",
  "diagnostics.otel.metrics": "OpenTelemetry Metrics Enabled",
  "diagnostics.otel.logs": "OpenTelemetry Logs Enabled",
  "diagnostics.otel.sampleRate": "OpenTelemetry Trace Sample Rate",
  "diagnostics.otel.flushIntervalMs": "OpenTelemetry Flush Interval (ms)",
  "diagnostics.cacheTrace.enabled": "Cache Trace Enabled",
  "diagnostics.cacheTrace.filePath": "Cache Trace File Path",
  "diagnostics.cacheTrace.includeMessages": "Cache Trace Include Messages",
  "diagnostics.cacheTrace.includePrompt": "Cache Trace Include Prompt",
  "diagnostics.cacheTrace.includeSystem": "Cache Trace Include System",
  "agents.list.*.identity.avatar": "Identity Avatar",
  "agents.list.*.skills": "Agent Skill Filter",
  "agents.list[].runtime": "Agent Runtime",
  "agents.list[].runtime.type": "Agent Runtime Type",
  "agents.list[].runtime.acp": "Agent ACP Runtime",
  "agents.list[].runtime.acp.agent": "Agent ACP Harness Agent",
  "agents.list[].runtime.acp.backend": "Agent ACP Backend",
  "agents.list[].runtime.acp.mode": "Agent ACP Mode",
  "agents.list[].runtime.acp.cwd": "Agent ACP Working Directory",
  "agents.list[].thinkingDefault": "Agent Thinking Default",
  "agents.list[].reasoningDefault": "Agent Reasoning Default",
  "agents.list[].fastModeDefault": "Agent Fast Mode Default",
  agents: "Agents",
  "agents.defaults": "Agent Defaults",
  "agents.list": "Agent List",
  gateway: "Gateway",
  "gateway.port": "Gateway Port",
  "gateway.mode": "Gateway Mode",
  "gateway.bind": "Gateway Bind Mode",
  "gateway.customBindHost": "Gateway Custom Bind Host",
  "gateway.controlUi": "Control UI",
  "gateway.controlUi.enabled": "Control UI Enabled",
  "gateway.auth": "Gateway Auth",
  "gateway.auth.mode": "Gateway Auth Mode",
  "gateway.auth.allowTailscale": "Gateway Auth Allow Tailscale Identity",
  "gateway.auth.rateLimit": "Gateway Auth Rate Limit",
  "gateway.auth.trustedProxy": "Gateway Trusted Proxy Auth",
  "gateway.trustedProxies": "Gateway Trusted Proxy CIDRs",
  "gateway.allowRealIpFallback": "Gateway Allow x-real-ip Fallback",
  "gateway.tools": "Gateway Tool Exposure Policy",
  "gateway.tools.allow": "Gateway Tool Allowlist",
  "gateway.tools.deny": "Gateway Tool Denylist",
  "gateway.channelHealthCheckMinutes": "Gateway Channel Health Check Interval (min)",
  "gateway.channelStaleEventThresholdMinutes": "Gateway Channel Stale Event Threshold (min)",
  "gateway.channelMaxRestartsPerHour": "Gateway Channel Max Restarts Per Hour",
  "gateway.tailscale": "Gateway Tailscale",
  "gateway.tailscale.mode": "Gateway Tailscale Mode",
  "gateway.tailscale.resetOnExit": "Gateway Tailscale Reset on Exit",
  "gateway.remote": "Remote Gateway",
  "gateway.remote.transport": "Remote Gateway Transport",
  "gateway.reload": "Config Reload",
  "gateway.tls": "Gateway TLS",
  "gateway.tls.enabled": "Gateway TLS Enabled",
  "gateway.tls.autoGenerate": "Gateway TLS Auto-Generate Cert",
  "gateway.tls.certPath": "Gateway TLS Certificate Path",
  "gateway.tls.keyPath": "Gateway TLS Key Path",
  "gateway.tls.caPath": "Gateway TLS CA Path",
  "gateway.http": "Gateway HTTP API",
  "gateway.http.endpoints": "Gateway HTTP Endpoints",
  "gateway.http.securityHeaders": "Gateway HTTP Security Headers",
  "gateway.http.securityHeaders.strictTransportSecurity": "Strict Transport Security Header",
  "gateway.remote.url": "Remote Gateway URL",
  "gateway.remote.sshTarget": "Remote Gateway SSH Target",
  "gateway.remote.sshIdentity": "Remote Gateway SSH Identity",
  "gateway.remote.token": "Remote Gateway Token",
  "gateway.remote.password": "Remote Gateway Password",
  "gateway.remote.tlsFingerprint": "Remote Gateway TLS Fingerprint",
  "gateway.auth.token": "Gateway Token",
  "gateway.auth.password": "Gateway Password",
  browser: "Browser",
  "browser.enabled": "Browser Enabled",
  "browser.cdpUrl": "Browser CDP URL",
  "browser.color": "Browser Accent Color",
  "browser.executablePath": "Browser Executable Path",
  "browser.headless": "Browser Headless Mode",
  "browser.noSandbox": "Browser No-Sandbox Mode",
  "browser.attachOnly": "Browser Attach-only Mode",
  "browser.cdpPortRangeStart": "Browser CDP Port Range Start",
  "browser.defaultProfile": "Browser Default Profile",
  "browser.profiles": "Browser Profiles",
  "browser.profiles.*.cdpPort": "Browser Profile CDP Port",
  "browser.profiles.*.cdpUrl": "Browser Profile CDP URL",
  "browser.profiles.*.userDataDir": "Browser Profile User Data Dir",
  "browser.profiles.*.driver": "Browser Profile Driver",
  "browser.profiles.*.attachOnly": "Browser Profile Attach-only Mode",
  "browser.profiles.*.color": "Browser Profile Accent Color",
  tools: "Tools",
  "tools.allow": "Tool Allowlist",
  "tools.deny": "Tool Denylist",
  "tools.web": "Web Tools",
  "tools.exec": "Exec Tool",
  "tools.media.image.enabled": "Enable Image Understanding",
  "tools.media.image.maxBytes": "Image Understanding Max Bytes",
  "tools.media.image.maxChars": "Image Understanding Max Chars",
  "tools.media.image.prompt": "Image Understanding Prompt",
  "tools.media.image.timeoutSeconds": "Image Understanding Timeout (sec)",
  "tools.media.image.attachments": "Image Understanding Attachment Policy",
  "tools.media.image.models": "Image Understanding Models",
  "tools.media.image.scope": "Image Understanding Scope",
  "tools.media.models": "Media Understanding Shared Models",
  "tools.media.concurrency": "Media Understanding Concurrency",
  ...MEDIA_AUDIO_FIELD_LABELS,
  "tools.media.video.enabled": "Enable Video Understanding",
  "tools.media.video.maxBytes": "Video Understanding Max Bytes",
  "tools.media.video.maxChars": "Video Understanding Max Chars",
  "tools.media.video.prompt": "Video Understanding Prompt",
  "tools.media.video.timeoutSeconds": "Video Understanding Timeout (sec)",
  "tools.media.video.attachments": "Video Understanding Attachment Policy",
  "tools.media.video.models": "Video Understanding Models",
  "tools.media.video.scope": "Video Understanding Scope",
  "tools.links.enabled": "Enable Link Understanding",
  "tools.links.maxLinks": "Link Understanding Max Links",
  "tools.links.timeoutSeconds": "Link Understanding Timeout (sec)",
  "tools.links.models": "Link Understanding Models",
  "tools.links.scope": "Link Understanding Scope",
  "tools.profile": "Tool Profile",
  "tools.alsoAllow": "Tool Allowlist Additions",
  "agents.list[].tools.profile": "Agent Tool Profile",
  "agents.list[].tools.alsoAllow": "Agent Tool Allowlist Additions",
  "tools.byProvider": "Tool Policy by Provider",
  "agents.list[].tools.byProvider": "Agent Tool Policy by Provider",
  "tools.exec.applyPatch.enabled": "Enable apply_patch",
  "tools.exec.applyPatch.workspaceOnly": "apply_patch Workspace-Only",
  "tools.exec.applyPatch.allowModels": "apply_patch Model Allowlist",
  "tools.loopDetection.enabled": "Tool-loop Detection",
  "tools.loopDetection.historySize": "Tool-loop History Size",
  "tools.loopDetection.warningThreshold": "Tool-loop Warning Threshold",
  "tools.loopDetection.criticalThreshold": "Tool-loop Critical Threshold",
  "tools.loopDetection.globalCircuitBreakerThreshold": "Tool-loop Global Circuit Breaker Threshold",
  "tools.loopDetection.detectors.genericRepeat": "Tool-loop Generic Repeat Detection",
  "tools.loopDetection.detectors.knownPollNoProgress": "Tool-loop Poll No-Progress Detection",
  "tools.loopDetection.detectors.pingPong": "Tool-loop Ping-Pong Detection",
  "tools.fs.workspaceOnly": "Workspace-only FS tools",
  "tools.sessions.visibility": "Session Tools Visibility",
  "tools.exec.notifyOnExit": "Exec Notify On Exit",
  "tools.exec.notifyOnExitEmptySuccess": "Exec Notify On Empty Success",
  "tools.exec.approvalRunningNoticeMs": "Exec Approval Running Notice (ms)",
  "tools.exec.host": "Exec Host",
  "tools.exec.security": "Exec Security",
  "tools.exec.ask": "Exec Ask",
  "tools.exec.node": "Exec Node Binding",
  "tools.agentToAgent": "Agent-to-Agent Tool Access",
  "tools.agentToAgent.enabled": "Enable Agent-to-Agent Tool",
  "tools.agentToAgent.allow": "Agent-to-Agent Target Allowlist",
  "tools.elevated": "Elevated Tool Access",
  "tools.elevated.enabled": "Enable Elevated Tool Access",
  "tools.elevated.allowFrom": "Elevated Tool Allow Rules",
  "tools.subagents": "Subagent Tool Policy",
  "tools.subagents.tools": "Subagent Tool Allow/Deny Policy",
  "tools.sandbox": "Sandbox Tool Policy",
  "tools.sandbox.tools": "Sandbox Tool Allow/Deny Policy",
  "tools.exec.pathPrepend": "Exec PATH Prepend",
  "tools.exec.safeBins": "Exec Safe Bins",
  "tools.exec.strictInlineEval": "Require Inline-Eval Approval",
  "tools.exec.safeBinTrustedDirs": "Exec Safe Bin Trusted Dirs",
  "tools.exec.safeBinProfiles": "Exec Safe Bin Profiles",
  approvals: "Approvals",
  "approvals.exec": "Exec Approval Forwarding",
  "approvals.exec.enabled": "Forward Exec Approvals",
  "approvals.exec.mode": "Approval Forwarding Mode",
  "approvals.exec.agentFilter": "Approval Agent Filter",
  "approvals.exec.sessionFilter": "Approval Session Filter",
  "approvals.exec.targets": "Approval Forwarding Targets",
  "approvals.exec.targets[].channel": "Approval Target Channel",
  "approvals.exec.targets[].to": "Approval Target Destination",
  "approvals.exec.targets[].accountId": "Approval Target Account ID",
  "approvals.exec.targets[].threadId": "Approval Target Thread ID",
  "tools.message.allowCrossContextSend": "Allow Cross-Context Messaging",
  "tools.message.crossContext.allowWithinProvider": "Allow Cross-Context (Same Provider)",
  "tools.message.crossContext.allowAcrossProviders": "Allow Cross-Context (Across Providers)",
  "tools.message.crossContext.marker.enabled": "Cross-Context Marker",
  "tools.message.crossContext.marker.prefix": "Cross-Context Marker Prefix",
  "tools.message.crossContext.marker.suffix": "Cross-Context Marker Suffix",
  "tools.message.broadcast.enabled": "Enable Message Broadcast",
  "tools.web.search.enabled": "Enable Web Search Tool",
  "tools.web.search.provider": "Web Search Provider",
  "tools.web.search.maxResults": "Web Search Max Results",
  "tools.web.search.timeoutSeconds": "Web Search Timeout (sec)",
  "tools.web.search.cacheTtlMinutes": "Web Search Cache TTL (min)",
  "tools.web.fetch.enabled": "Enable Web Fetch Tool",
  "tools.web.fetch.maxChars": "Web Fetch Max Chars",
  "tools.web.fetch.maxCharsCap": "Web Fetch Hard Max Chars",
  "tools.web.fetch.timeoutSeconds": "Web Fetch Timeout (sec)",
  "tools.web.fetch.cacheTtlMinutes": "Web Fetch Cache TTL (min)",
  "tools.web.fetch.maxRedirects": "Web Fetch Max Redirects",
  "tools.web.fetch.userAgent": "Web Fetch User-Agent",
  "tools.web.fetch.readability": "Web Fetch Readability Extraction",
  "tools.web.fetch.firecrawl.enabled": "Enable Firecrawl Fallback",
  "tools.web.fetch.firecrawl.apiKey": "Firecrawl API Key", // pragma: allowlist secret
  "tools.web.fetch.firecrawl.baseUrl": "Firecrawl Base URL",
  "tools.web.fetch.firecrawl.onlyMainContent": "Firecrawl Main Content Only",
  "tools.web.fetch.firecrawl.maxAgeMs": "Firecrawl Cache Max Age (ms)",
  "tools.web.fetch.firecrawl.timeoutSeconds": "Firecrawl Timeout (sec)",
  "gateway.controlUi.basePath": "Control UI Base Path",
  "gateway.controlUi.root": "Control UI Assets Root",
  "gateway.controlUi.allowedOrigins": "Control UI Allowed Origins",
  "gateway.controlUi.dangerouslyAllowHostHeaderOriginFallback":
    "危险地允许 Host-Header 来源回退",
  "gateway.controlUi.allowInsecureAuth": "控制面板不安全认证开关",
  "gateway.controlUi.dangerouslyDisableDeviceAuth": "危险地禁用控制面板设备认证",
  "gateway.http.endpoints.chatCompletions.enabled": "OpenAI 聊天补全端点",
  "gateway.http.endpoints.chatCompletions.maxBodyBytes": "OpenAI 聊天补全最大请求体字节数",
  "gateway.http.endpoints.chatCompletions.maxImageParts": "OpenAI 聊天补全最大图片分块数",
  "gateway.http.endpoints.chatCompletions.maxTotalImageBytes":
    "OpenAI 聊天补全最大图片总字节数",
  "gateway.http.endpoints.chatCompletions.images": "OpenAI 聊天补全图片限制",
  "gateway.http.endpoints.chatCompletions.images.allowUrl":
    "OpenAI 聊天补全允许图片 URL",
  "gateway.http.endpoints.chatCompletions.images.urlAllowlist":
    "OpenAI 聊天补全图片 URL 允许列表",
  "gateway.http.endpoints.chatCompletions.images.allowedMimes":
    "OpenAI 聊天补全图片 MIME 允许列表",
  "gateway.http.endpoints.chatCompletions.images.maxBytes":
    "OpenAI 聊天补全图片最大字节数",
  "gateway.http.endpoints.chatCompletions.images.maxRedirects":
    "OpenAI 聊天补全图片最大重定向次数",
  "gateway.http.endpoints.chatCompletions.images.timeoutMs":
    "OpenAI Chat Completions Image Timeout (ms)",
  "gateway.reload.mode": "Config Reload Mode",
  "gateway.reload.debounceMs": "Config Reload Debounce (ms)",
  "gateway.reload.deferralTimeoutMs": "Restart Deferral Timeout (ms)",
  "gateway.nodes.browser.mode": "Gateway Node Browser Mode",
  "gateway.nodes.browser.node": "Gateway Node Browser Pin",
  "gateway.nodes.allowCommands": "Gateway Node Allowlist (Extra Commands)",
  "gateway.nodes.denyCommands": "Gateway Node Denylist",
  nodeHost: "Node Host",
  "nodeHost.browserProxy": "Node Browser Proxy",
  "nodeHost.browserProxy.enabled": "Node Browser Proxy Enabled",
  "nodeHost.browserProxy.allowProfiles": "Node Browser Proxy Allowed Profiles",
  media: "Media",
  "media.preserveFilenames": "Preserve Media Filenames",
  "media.ttlHours": "Media Retention TTL (hours)",
  audio: "Audio",
  "audio.transcription": "Audio Transcription",
  "audio.transcription.command": "Audio Transcription Command",
  "audio.transcription.timeoutSeconds": "Audio Transcription Timeout (sec)",
  bindings: "Bindings",
  "bindings[].type": "Binding Type",
  "bindings[].agentId": "Binding Agent ID",
  "bindings[].match": "Binding Match Rule",
  "bindings[].match.channel": "Binding Channel",
  "bindings[].match.accountId": "Binding Account ID",
  "bindings[].match.peer": "Binding Peer Match",
  "bindings[].match.peer.kind": "Binding Peer Kind",
  "bindings[].match.peer.id": "Binding Peer ID",
  "bindings[].match.guildId": "Binding Guild ID",
  "bindings[].match.teamId": "Binding Team ID",
  "bindings[].match.roles": "Binding Roles",
  "bindings[].acp": "ACP Binding Overrides",
  "bindings[].acp.mode": "ACP Binding Mode",
  "bindings[].acp.label": "ACP Binding Label",
  "bindings[].acp.cwd": "ACP Binding Working Directory",
  "bindings[].acp.backend": "ACP Binding Backend",
  broadcast: "Broadcast",
  "broadcast.strategy": "Broadcast Strategy",
  "broadcast.*": "Broadcast Destination List",
  "skills.load.watch": "Watch Skills",
  "skills.load.watchDebounceMs": "Skills Watch Debounce (ms)",
  "agents.defaults.workspace": "Workspace",
  "agents.defaults.repoRoot": "Repo Root",
  "agents.defaults.bootstrapMaxChars": "Bootstrap Max Chars",
  "agents.defaults.bootstrapTotalMaxChars": "Bootstrap Total Max Chars",
  "agents.defaults.bootstrapPromptTruncationWarning": "Bootstrap Prompt Truncation Warning",
  "agents.defaults.envelopeTimezone": "Envelope Timezone",
  "agents.defaults.envelopeTimestamp": "Envelope Timestamp",
  "agents.defaults.envelopeElapsed": "Envelope Elapsed",
  "agents.defaults.memorySearch": "Memory Search",
  "agents.defaults.memorySearch.enabled": "Enable Memory Search",
  "agents.defaults.memorySearch.sources": "Memory Search Sources",
  "agents.defaults.memorySearch.extraPaths": "Extra Memory Paths",
  "agents.defaults.memorySearch.multimodal": "Memory Search Multimodal",
  "agents.defaults.memorySearch.multimodal.enabled": "Enable Memory Search Multimodal",
  "agents.defaults.memorySearch.multimodal.modalities": "Memory Search Multimodal Modalities",
  "agents.defaults.memorySearch.multimodal.maxFileBytes": "Memory Search Multimodal Max File Bytes",
  "agents.defaults.memorySearch.experimental.sessionMemory":
    "记忆搜索会话索引（实验性）",
  "agents.defaults.memorySearch.provider": "记忆搜索提供者",
  "agents.defaults.memorySearch.remote.baseUrl": "远程嵌入基础 URL",
  "agents.defaults.memorySearch.remote.apiKey": "远程嵌入 API 密钥",
  "agents.defaults.memorySearch.remote.headers": "远程嵌入请求头",
  "agents.defaults.memorySearch.remote.batch.enabled": "启用远程批量嵌入",
  "agents.defaults.memorySearch.remote.batch.wait": "远程批量等待完成",
  "agents.defaults.memorySearch.remote.batch.concurrency": "远程批量并发数",
  "agents.defaults.memorySearch.remote.batch.pollIntervalMs": "远程批量轮询间隔（毫秒）",
  "agents.defaults.memorySearch.remote.batch.timeoutMinutes": "远程批量超时（分钟）",
  "agents.defaults.memorySearch.model": "记忆搜索模型",
  "agents.defaults.memorySearch.outputDimensionality": "记忆搜索输出维度",
  "agents.defaults.memorySearch.fallback": "记忆搜索回退",
  "agents.defaults.memorySearch.local.modelPath": "本地嵌入模型路径",
  "agents.defaults.memorySearch.store.path": "记忆搜索索引路径",
  "agents.defaults.memorySearch.store.vector.enabled": "记忆搜索向量索引",
  "agents.defaults.memorySearch.store.vector.extensionPath": "记忆搜索向量扩展路径",
  "agents.defaults.memorySearch.chunking.tokens": "记忆分块令牌数",
  "agents.defaults.memorySearch.chunking.overlap": "记忆分块重叠令牌数",
  "agents.defaults.memorySearch.sync.onSessionStart": "会话开始时索引",
  "agents.defaults.memorySearch.sync.onSearch": "搜索时索引（懒加载）",
  "agents.defaults.memorySearch.sync.watch": "监听记忆文件",
  "agents.defaults.memorySearch.sync.watchDebounceMs": "记忆监听防抖（毫秒）",
  "agents.defaults.memorySearch.sync.sessions.deltaBytes": "会话增量字节数",
  "agents.defaults.memorySearch.sync.sessions.deltaMessages": "会话增量消息数",
  "agents.defaults.memorySearch.query.maxResults": "记忆搜索最大结果数",
  "agents.defaults.memorySearch.query.minScore": "记忆搜索最低分数",
  "agents.defaults.memorySearch.query.hybrid.enabled": "记忆搜索混合模式",
  "agents.defaults.memorySearch.query.hybrid.vectorWeight": "记忆搜索向量权重",
  "agents.defaults.memorySearch.query.hybrid.textWeight": "记忆搜索文本权重",
  "agents.defaults.memorySearch.query.hybrid.candidateMultiplier":
    "记忆搜索混合候选倍数",
  "agents.defaults.memorySearch.query.hybrid.mmr.enabled": "记忆搜索 MMR 重排序",
  "agents.defaults.memorySearch.query.hybrid.mmr.lambda": "记忆搜索 MMR Lambda",
  "agents.defaults.memorySearch.query.hybrid.temporalDecay.enabled": "记忆搜索时间衰减",
  "agents.defaults.memorySearch.query.hybrid.temporalDecay.halfLifeDays":
    "记忆搜索时间衰减半衰期（天）",
  "agents.defaults.memorySearch.cache.enabled": "记忆搜索嵌入缓存",
  "agents.defaults.memorySearch.cache.maxEntries": "记忆搜索嵌入缓存最大条目数",
  memory: "记忆",
  "memory.backend": "记忆后端",
  "memory.citations": "记忆引用模式",
  "memory.qmd.command": "QMD 二进制",
  "memory.qmd.mcporter": "QMD MCPorter",
  "memory.qmd.mcporter.enabled": "启用 QMD MCPorter",
  "memory.qmd.mcporter.serverName": "QMD MCPorter 服务器名称",
  "memory.qmd.mcporter.startDaemon": "QMD MCPorter 启动守护进程",
  "memory.qmd.searchMode": "QMD 搜索模式",
  "memory.qmd.includeDefaultMemory": "QMD 包含默认记忆",
  "memory.qmd.paths": "QMD 额外路径",
  "memory.qmd.paths.path": "QMD 路径",
  "memory.qmd.paths.pattern": "QMD 路径模式",
  "memory.qmd.paths.name": "QMD 路径名称",
  "memory.qmd.sessions.enabled": "QMD 会话索引",
  "memory.qmd.sessions.exportDir": "QMD 会话导出目录",
  "memory.qmd.sessions.retentionDays": "QMD 会话保留（天）",
  "memory.qmd.update.interval": "QMD 更新间隔",
  "memory.qmd.update.debounceMs": "QMD 更新防抖（毫秒）",
  "memory.qmd.update.onBoot": "启动时 QMD 更新",
  "memory.qmd.update.waitForBootSync": "QMD 等待启动同步",
  "memory.qmd.update.embedInterval": "QMD 嵌入间隔",
  "memory.qmd.update.commandTimeoutMs": "QMD 命令超时（毫秒）",
  "memory.qmd.update.updateTimeoutMs": "QMD 更新超时（毫秒）",
  "memory.qmd.update.embedTimeoutMs": "QMD 嵌入超时（毫秒）",
  "memory.qmd.limits.maxResults": "QMD 最大结果数",
  "memory.qmd.limits.maxSnippetChars": "QMD 最大片段字符数",
  "memory.qmd.limits.maxInjectedChars": "QMD 最大注入字符数",
  "memory.qmd.limits.timeoutMs": "QMD 搜索超时（毫秒）",
  "memory.qmd.scope": "QMD 展示范围",
  auth: "认证",
  "auth.profiles": "认证配置",
  "auth.order": "认证配置顺序",
  "auth.cooldowns": "认证冷却",
  acp: "ACP",
  "acp.enabled": "ACP Enabled",
  "acp.dispatch.enabled": "ACP Dispatch Enabled",
  "acp.backend": "ACP Backend",
  "acp.defaultAgent": "ACP Default Agent",
  "acp.allowedAgents": "ACP Allowed Agents",
  "acp.maxConcurrentSessions": "ACP Max Concurrent Sessions",
  "acp.stream": "ACP Stream",
  "acp.stream.coalesceIdleMs": "ACP Stream Coalesce Idle (ms)",
  "acp.stream.maxChunkChars": "ACP Stream Max Chunk Chars",
  "acp.stream.repeatSuppression": "ACP Stream Repeat Suppression",
  "acp.stream.deliveryMode": "ACP Stream Delivery Mode",
  "acp.stream.hiddenBoundarySeparator": "ACP Stream Hidden Boundary Separator",
  "acp.stream.maxOutputChars": "ACP Stream Max Output Chars",
  "acp.stream.maxSessionUpdateChars": "ACP Stream Max Session Update Chars",
  "acp.stream.tagVisibility": "ACP Stream Tag Visibility",
  "acp.runtime.ttlMinutes": "ACP Runtime TTL (minutes)",
  "acp.runtime.installCommand": "ACP Runtime Install Command",
  models: "Models",
  "models.mode": "Model Catalog Mode",
  "models.providers": "Model Providers",
  "models.providers.*.baseUrl": "Model Provider Base URL",
  "models.providers.*.apiKey": "Model Provider API Key", // pragma: allowlist secret
  "models.providers.*.auth": "Model Provider Auth Mode",
  "models.providers.*.api": "Model Provider API Adapter",
  "models.providers.*.injectNumCtxForOpenAICompat": "Model Provider Inject num_ctx (OpenAI Compat)",
  "models.providers.*.headers": "Model Provider Headers",
  "models.providers.*.authHeader": "Model Provider Authorization Header",
  "models.providers.*.models": "Model Provider Model List",
  "models.bedrockDiscovery": "Bedrock Model Discovery",
  "models.bedrockDiscovery.enabled": "Bedrock Discovery Enabled",
  "models.bedrockDiscovery.region": "Bedrock Discovery Region",
  "models.bedrockDiscovery.providerFilter": "Bedrock Discovery Provider Filter",
  "models.bedrockDiscovery.refreshInterval": "Bedrock Discovery Refresh Interval (s)",
  "models.bedrockDiscovery.defaultContextWindow": "Bedrock Default Context Window",
  "models.bedrockDiscovery.defaultMaxTokens": "Bedrock Default Max Tokens",
  "auth.cooldowns.billingBackoffHours": "Billing Backoff (hours)",
  "auth.cooldowns.billingBackoffHoursByProvider": "Billing Backoff Overrides",
  "auth.cooldowns.billingMaxHours": "Billing Backoff Cap (hours)",
  "auth.cooldowns.failureWindowHours": "Failover Window (hours)",
  "agents.defaults.models": "Models",
  "agents.defaults.model.primary": "Primary Model",
  "agents.defaults.model.fallbacks": "Model Fallbacks",
  "agents.defaults.imageModel.primary": "Image Model",
  "agents.defaults.imageModel.fallbacks": "Image Model Fallbacks",
  "agents.defaults.imageGenerationModel.primary": "Image Generation Model",
  "agents.defaults.imageGenerationModel.fallbacks": "Image Generation Model Fallbacks",
  "agents.defaults.pdfModel.primary": "PDF Model",
  "agents.defaults.pdfModel.fallbacks": "PDF Model Fallbacks",
  "agents.defaults.pdfMaxBytesMb": "PDF Max Size (MB)",
  "agents.defaults.pdfMaxPages": "PDF Max Pages",
  "agents.defaults.imageMaxDimensionPx": "Image Max Dimension (px)",
  "agents.defaults.humanDelay.mode": "Human Delay Mode",
  "agents.defaults.humanDelay.minMs": "Human Delay Min (ms)",
  "agents.defaults.humanDelay.maxMs": "Human Delay Max (ms)",
  "agents.defaults.cliBackends": "CLI Backends",
  "agents.defaults.compaction": "Compaction",
  "agents.defaults.compaction.mode": "Compaction Mode",
  "agents.defaults.compaction.reserveTokens": "Compaction Reserve Tokens",
  "agents.defaults.compaction.keepRecentTokens": "Compaction Keep Recent Tokens",
  "agents.defaults.compaction.reserveTokensFloor": "Compaction Reserve Token Floor",
  "agents.defaults.compaction.maxHistoryShare": "Compaction Max History Share",
  "agents.defaults.compaction.identifierPolicy": "Compaction Identifier Policy",
  "agents.defaults.compaction.identifierInstructions": "Compaction Identifier Instructions",
  "agents.defaults.compaction.recentTurnsPreserve": "Compaction Preserve Recent Turns",
  "agents.defaults.compaction.qualityGuard": "Compaction Quality Guard",
  "agents.defaults.compaction.qualityGuard.enabled": "Compaction Quality Guard Enabled",
  "agents.defaults.compaction.qualityGuard.maxRetries": "Compaction Quality Guard Max Retries",
  "agents.defaults.compaction.postIndexSync": "Compaction Post-Index Sync",
  "agents.defaults.compaction.postCompactionSections": "Post-Compaction Context Sections",
  "agents.defaults.compaction.timeoutSeconds": "Compaction Timeout (Seconds)",
  "agents.defaults.compaction.model": "Compaction Model Override",
  "agents.defaults.compaction.truncateAfterCompaction": "Truncate After Compaction",
  "agents.defaults.compaction.memoryFlush": "Compaction Memory Flush",
  "agents.defaults.compaction.memoryFlush.enabled": "Compaction Memory Flush Enabled",
  "agents.defaults.compaction.memoryFlush.softThresholdTokens":
    "压缩记忆刷新软阈值",
  "agents.defaults.compaction.memoryFlush.forceFlushTranscriptBytes":
    "压缩记忆刷新转录大小阈值",
  "agents.defaults.compaction.memoryFlush.prompt": "压缩记忆刷新提示词",
  "agents.defaults.compaction.memoryFlush.systemPrompt": "压缩记忆刷新系统提示词",
  "agents.defaults.embeddedPi": "嵌入式 Pi",
  "agents.defaults.embeddedPi.projectSettingsPolicy": "嵌入式 Pi 项目设置策略",
  "agents.defaults.heartbeat.directPolicy": "心跳直接策略",
  "agents.list.*.heartbeat.directPolicy": "心跳直接策略",
  "agents.defaults.heartbeat.suppressToolErrorWarnings": "心跳抑制工具错误警告",
  "agents.defaults.sandbox.browser.network": "沙箱浏览器网络",
  "agents.defaults.sandbox.browser.cdpSourceRange": "沙箱浏览器 CDP 源端口范围",
  "agents.defaults.sandbox.docker.dangerouslyAllowContainerNamespaceJoin":
    "Sandbox Docker Allow Container Namespace Join",
  commands: "Commands",
  "commands.native": "Native Commands",
  "commands.nativeSkills": "Native Skill Commands",
  "commands.text": "Text Commands",
  "commands.bash": "Allow Bash Chat Command",
  "commands.bashForegroundMs": "Bash Foreground Window (ms)",
  "commands.config": "Allow /config",
  "commands.mcp": "Allow /mcp",
  "commands.plugins": "Allow /plugins",
  "commands.debug": "Allow /debug",
  "commands.restart": "Allow Restart",
  "commands.useAccessGroups": "Use Access Groups",
  "commands.ownerAllowFrom": "Command Owners",
  "commands.ownerDisplay": "Owner ID Display",
  "commands.ownerDisplaySecret": "Owner ID Hash Secret", // pragma: allowlist secret
  "commands.allowFrom": "Command Elevated Access Rules",
  mcp: "MCP",
  "mcp.servers": "MCP Servers",
  ui: "UI",
  "ui.seamColor": "主题色",
  "ui.assistant": "助手外观",
  "ui.assistant.name": "助手名称",
  "ui.assistant.avatar": "助手头像",
  "browser.evaluateEnabled": "启用浏览器执行",
  "browser.snapshotDefaults": "浏览器快照默认值",
  "browser.snapshotDefaults.mode": "浏览器快照模式",
  "browser.ssrfPolicy": "浏览器 SSRF 策略",
  "browser.ssrfPolicy.allowPrivateNetwork": "浏览器允许专用网络",
  "browser.ssrfPolicy.dangerouslyAllowPrivateNetwork": "浏览器危险地允许专用网络",
  "browser.ssrfPolicy.allowedHostnames": "浏览器允许的主机名",
  "browser.ssrfPolicy.hostnameAllowlist": "浏览器主机名允许列表",
  "browser.remoteCdpTimeoutMs": "远程 CDP 超时（毫秒）",
  "browser.remoteCdpHandshakeTimeoutMs": "远程 CDP 握手超时（毫秒）",
  session: "会话",
  "session.scope": "会话范围",
  "session.dmScope": "私信会话范围",
  "session.identityLinks": "会话身份链接",
  "session.resetTriggers": "会话重置触发器",
  "session.idleMinutes": "会话空闲分钟",
  "session.reset": "会话重置策略",
  "session.reset.mode": "会话重置模式",
  "session.reset.atHour": "会话每日重置时间",
  "session.reset.idleMinutes": "会话重置空闲分钟",
  "session.resetByType": "按聊天类型重置会话",
  "session.resetByType.direct": "会话重置（直接）",
  "session.resetByType.dm": "会话重置（私信已弃用别名）",
  "session.resetByType.group": "会话重置（群组）",
  "session.resetByType.thread": "会话重置（线程）",
  "session.resetByChannel": "按通道重置会话",
  "session.store": "会话存储路径",
  "session.typingIntervalSeconds": "会话输入间隔（秒）",
  "session.typingMode": "会话输入模式",
  "session.parentForkMaxTokens": "会话父分支最大令牌数",
  "session.mainKey": "会话主键",
  "session.sendPolicy": "会话发送策略",
  "session.sendPolicy.default": "会话发送策略默认操作",
  "session.sendPolicy.rules": "会话发送策略规则",
  "session.sendPolicy.rules[].action": "会话发送规则操作",
  "session.sendPolicy.rules[].match": "会话发送规则匹配",
  "session.sendPolicy.rules[].match.channel": "会话发送规则通道",
  "session.sendPolicy.rules[].match.chatType": "会话发送规则聊天类型",
  "session.sendPolicy.rules[].match.keyPrefix": "会话发送规则键前缀",
  "session.sendPolicy.rules[].match.rawKeyPrefix": "会话发送规则原始键前缀",
  "session.agentToAgent": "会话代理间",
  "session.agentToAgent.maxPingPongTurns": "代理间乒乓轮次",
  "session.threadBindings": "会话线程绑定",
  "session.threadBindings.enabled": "启用线程绑定",
  "session.threadBindings.idleHours": "线程绑定空闲超时（小时）",
  "session.threadBindings.maxAgeHours": "线程绑定最大存活时间（小时）",
  "session.maintenance": "会话维护",
  "session.maintenance.mode": "会话维护模式",
  "session.maintenance.pruneAfter": "会话修剪时间",
  "session.maintenance.pruneDays": "会话修剪天数（已弃用）",
  "session.maintenance.maxEntries": "会话最大条目数",
  "session.maintenance.rotateBytes": "会话轮转大小",
  "session.maintenance.resetArchiveRetention": "会话重置归档保留",
  "session.maintenance.maxDiskBytes": "会话最大磁盘预算",
  "session.maintenance.highWaterBytes": "会话磁盘高水位目标",
  cron: "定时任务",
  "cron.enabled": "启用定时任务",
  "cron.store": "定时任务存储路径",
  "cron.maxConcurrentRuns": "定时任务最大并发运行",
  "cron.retry": "定时任务重试策略",
  "cron.retry.maxAttempts": "定时任务最大重试次数",
  "cron.retry.backoffMs": "定时任务重试退避（毫秒）",
  "cron.retry.retryOn": "定时任务重试错误类型",
  "cron.webhook": "定时任务旧版 Webhook（已弃用）",
  "cron.webhookToken": "定时任务 Webhook Bearer 令牌",
  "cron.sessionRetention": "定时任务会话保留",
  "cron.runLog": "定时任务运行日志修剪",
  "cron.runLog.maxBytes": "定时任务运行日志最大字节数",
  "cron.runLog.keepLines": "定时任务运行日志保留行数",
  hooks: "钩子",
  "hooks.enabled": "启用钩子",
  "hooks.path": "钩子端点路径",
  "hooks.token": "钩子认证令牌",
  "hooks.defaultSessionKey": "钩子默认会话键",
  "hooks.allowRequestSessionKey": "钩子允许请求会话键",
  "hooks.allowedSessionKeyPrefixes": "钩子允许的会话键前缀",
  "hooks.allowedAgentIds": "钩子允许的代理 ID",
  "hooks.maxBodyBytes": "钩子最大请求体字节数",
  "hooks.presets": "钩子预设",
  "hooks.transformsDir": "钩子转换目录",
  "hooks.mappings": "钩子映射",
  "hooks.mappings[].id": "钩子映射 ID",
  "hooks.mappings[].match": "钩子映射匹配",
  "hooks.mappings[].match.path": "钩子映射匹配路径",
  "hooks.mappings[].match.source": "钩子映射匹配来源",
  "hooks.mappings[].action": "钩子映射操作",
  "hooks.mappings[].wakeMode": "钩子映射唤醒模式",
  "hooks.mappings[].name": "钩子映射名称",
  "hooks.mappings[].agentId": "钩子映射代理 ID",
  "hooks.mappings[].sessionKey": "钩子映射会话键",
  "hooks.mappings[].messageTemplate": "钩子映射消息模板",
  "hooks.mappings[].textTemplate": "钩子映射文本模板",
  "hooks.mappings[].deliver": "钩子映射投递回复",
  "hooks.mappings[].allowUnsafeExternalContent": "钩子映射允许不安全外部内容",
  "hooks.mappings[].channel": "钩子映射投递通道",
  "hooks.mappings[].to": "钩子映射投递目标",
  "hooks.mappings[].model": "钩子映射模型覆盖",
  "hooks.mappings[].thinking": "钩子映射思考覆盖",
  "hooks.mappings[].timeoutSeconds": "钩子映射超时（秒）",
  "hooks.mappings[].transform": "钩子映射转换",
  "hooks.mappings[].transform.module": "钩子转换模块",
  "hooks.mappings[].transform.export": "钩子转换导出",
  "hooks.gmail": "Gmail 钩子",
  "hooks.gmail.account": "Gmail 钩子账户",
  "hooks.gmail.label": "Gmail 钩子标签",
  "hooks.gmail.topic": "Gmail 钩子发布/订阅主题",
  "hooks.gmail.subscription": "Gmail 钩子订阅",
  "hooks.gmail.pushToken": "Gmail 钩子推送令牌",
  "hooks.gmail.hookUrl": "Gmail 钩子回调 URL",
  "hooks.gmail.includeBody": "Gmail 钩子包含正文",
  "hooks.gmail.maxBytes": "Gmail 钩子最大正文字节数",
  "hooks.gmail.renewEveryMinutes": "Gmail 钩子续订间隔（分钟）",
  "hooks.gmail.allowUnsafeExternalContent": "Gmail 钩子允许不安全外部内容",
  "hooks.gmail.serve": "Gmail 钩子本地服务器",
  "hooks.gmail.serve.bind": "Gmail 钩子服务器绑定地址",
  "hooks.gmail.serve.port": "Gmail 钩子服务器端口",
  "hooks.gmail.serve.path": "Gmail 钩子服务器路径",
  "hooks.gmail.tailscale": "Gmail 钩子 Tailscale",
  "hooks.gmail.tailscale.mode": "Gmail 钩子 Tailscale 模式",
  "hooks.gmail.tailscale.path": "Gmail 钩子 Tailscale 路径",
  "hooks.gmail.tailscale.target": "Gmail 钩子 Tailscale 目标",
  "hooks.gmail.model": "Gmail 钩子模型覆盖",
  "hooks.gmail.thinking": "Gmail 钩子思考覆盖",
  "hooks.internal": "内部钩子",
  "hooks.internal.enabled": "启用内部钩子",
  "hooks.internal.handlers": "内部钩子处理器",
  "hooks.internal.handlers[].event": "内部钩子事件",
  "hooks.internal.handlers[].module": "内部钩子模块",
  "hooks.internal.handlers[].export": "内部钩子导出",
  "hooks.internal.entries": "内部钩子条目",
  "hooks.internal.load": "内部钩子加载器",
  "hooks.internal.load.extraDirs": "内部钩子额外目录",
  "hooks.internal.installs": "内部钩子安装记录",
  web: "Web 通道",
  "web.enabled": "启用 Web 通道",
  "web.heartbeatSeconds": "Web 通道心跳间隔（秒）",
  "web.reconnect": "Web 通道重连策略",
  "web.reconnect.initialMs": "Web 重连初始延迟（毫秒）",
  "web.reconnect.maxMs": "Web 重连最大延迟（毫秒）",
  "web.reconnect.factor": "Web 重连退避因子",
  "web.reconnect.jitter": "Web 重连抖动",
  "web.reconnect.maxAttempts": "Web 重连最大尝试次数",
  discovery: "发现",
  "discovery.wideArea": "广域发现",
  "discovery.wideArea.enabled": "启用广域发现",
  "discovery.mdns": "mDNS 发现",
  canvasHost: "画布主机",
  "canvasHost.enabled": "启用画布主机",
  "canvasHost.root": "画布主机根目录",
  "canvasHost.port": "画布主机端口",
  "canvasHost.liveReload": "画布主机实时重载",
  talk: "语音",
  "talk.voiceId": "语音 ID",
  "talk.voiceAliases": "语音别名",
  "talk.modelId": "语音模型 ID",
  "talk.outputFormat": "语音输出格式",
  "talk.interruptOnSpeech": "语音打断",
  "talk.silenceTimeoutMs": "语音静默超时（毫秒）",
  messages: "消息",
  "messages.messagePrefix": "入站消息前缀",
  "messages.responsePrefix": "出站响应前缀",
  "messages.groupChat": "群聊规则",
  "messages.groupChat.mentionPatterns": "群组提及模式",
  "messages.groupChat.historyLimit": "群组历史限制",
  "messages.queue": "入站队列",
  "messages.queue.mode": "队列模式",
  "messages.queue.byChannel": "按通道队列模式",
  "messages.queue.debounceMs": "队列防抖（毫秒）",
  "messages.queue.debounceMsByChannel": "按通道队列防抖（毫秒）",
  "messages.queue.cap": "队列容量",
  "messages.queue.drop": "队列丢弃策略",
  "messages.inbound": "入站防抖",
  "messages.suppressToolErrors": "抑制工具错误警告",
  "messages.ackReaction": "确认反应表情",
  "messages.ackReactionScope": "确认反应范围",
  "messages.removeAckAfterReply": "回复后移除确认反应",
  "messages.statusReactions": "状态反应",
  "messages.statusReactions.enabled": "启用状态反应",
  "messages.statusReactions.emojis": "状态反应表情",
  "messages.statusReactions.timing": "状态反应时机",
  "messages.inbound.debounceMs": "入站消息防抖（毫秒）",
  "messages.inbound.byChannel": "按通道入站防抖（毫秒）",
  "messages.tts": "消息文字转语音",
  "talk.provider": "语音活跃提供者",
  "talk.providers": "语音提供者设置",
  "talk.providers.*.voiceId": "语音提供者语音 ID",
  "talk.providers.*.voiceAliases": "语音提供者语音别名",
  "talk.providers.*.modelId": "语音提供者模型 ID",
  "talk.providers.*.outputFormat": "语音提供者输出格式",
  "talk.providers.*.apiKey": "语音提供者 API 密钥", // pragma: allowlist secret
  "talk.apiKey": "语音 API 密钥", // pragma: allowlist secret
  channels: "通道",
  "channels.defaults": "通道默认值",
  "channels.defaults.groupPolicy": "默认群组策略",
  "channels.defaults.heartbeat": "默认心跳可见性",
  "channels.defaults.heartbeat.showOk": "心跳显示正常",
  "channels.defaults.heartbeat.showAlerts": "心跳显示警报",
  "channels.defaults.heartbeat.useIndicator": "心跳使用指示器",
  "channels.whatsapp": "WhatsApp",
  "channels.telegram": "Telegram",
  "channels.telegram.customCommands": "Telegram 自定义命令",
  "channels.discord": "Discord",
  "channels.slack": "Slack",
  "channels.mattermost": "Mattermost",
  "channels.signal": "Signal",
  "channels.imessage": "iMessage",
  "channels.bluebubbles": "BlueBubbles",
  "channels.msteams": "MS Teams",
  "channels.modelByChannel": "通道模型覆盖",
  ...IRC_FIELD_LABELS,
  "channels.telegram.botToken": "Telegram Bot Token",
  "channels.telegram.dmPolicy": "Telegram DM Policy",
  "channels.telegram.configWrites": "Telegram Config Writes",
  "channels.telegram.commands.native": "Telegram Native Commands",
  "channels.telegram.commands.nativeSkills": "Telegram Native Skill Commands",
  "channels.telegram.streaming": "Telegram Streaming Mode",
  "channels.telegram.retry.attempts": "Telegram Retry Attempts",
  "channels.telegram.retry.minDelayMs": "Telegram Retry Min Delay (ms)",
  "channels.telegram.retry.maxDelayMs": "Telegram Retry Max Delay (ms)",
  "channels.telegram.retry.jitter": "Telegram Retry Jitter",
  "channels.telegram.network.autoSelectFamily": "Telegram autoSelectFamily",
  "channels.telegram.timeoutSeconds": "Telegram API Timeout (seconds)",
  "channels.telegram.silentErrorReplies": "Telegram Silent Error Replies",
  "channels.telegram.apiRoot": "Telegram API Root URL",
  "channels.telegram.autoTopicLabel": "Telegram Auto Topic Label",
  "channels.telegram.autoTopicLabel.enabled": "Telegram Auto Topic Label Enabled",
  "channels.telegram.autoTopicLabel.prompt": "Telegram Auto Topic Label Prompt",
  "channels.telegram.capabilities.inlineButtons": "Telegram Inline Buttons",
  "channels.telegram.execApprovals": "Telegram Exec Approvals",
  "channels.telegram.execApprovals.enabled": "Telegram Exec Approvals Enabled",
  "channels.telegram.execApprovals.approvers": "Telegram Exec Approval Approvers",
  "channels.telegram.execApprovals.agentFilter": "Telegram Exec Approval Agent Filter",
  "channels.telegram.execApprovals.sessionFilter": "Telegram Exec Approval Session Filter",
  "channels.telegram.execApprovals.target": "Telegram Exec Approval Target",
  "channels.telegram.threadBindings.enabled": "Telegram Thread Binding Enabled",
  "channels.telegram.threadBindings.idleHours": "Telegram Thread Binding Idle Timeout (hours)",
  "channels.telegram.threadBindings.maxAgeHours": "Telegram Thread Binding Max Age (hours)",
  "channels.telegram.threadBindings.spawnSubagentSessions": "Telegram Thread-Bound Subagent Spawn",
  "channels.telegram.threadBindings.spawnAcpSessions": "Telegram Thread-Bound ACP Spawn",
  "channels.whatsapp.dmPolicy": "WhatsApp DM Policy",
  "channels.whatsapp.selfChatMode": "WhatsApp Self-Phone Mode",
  "channels.whatsapp.debounceMs": "WhatsApp Message Debounce (ms)",
  "channels.whatsapp.configWrites": "WhatsApp Config Writes",
  "channels.signal.dmPolicy": "Signal DM Policy",
  "channels.signal.configWrites": "Signal Config Writes",
  "channels.imessage.dmPolicy": "iMessage DM Policy",
  "channels.imessage.configWrites": "iMessage Config Writes",
  "channels.bluebubbles.dmPolicy": "BlueBubbles DM Policy",
  "channels.msteams.configWrites": "MS Teams Config Writes",
  "channels.irc.configWrites": "IRC Config Writes",
  "channels.discord.dmPolicy": "Discord DM Policy",
  "channels.discord.dm.policy": "Discord DM Policy",
  "channels.discord.configWrites": "Discord Config Writes",
  "channels.discord.proxy": "Discord Proxy URL",
  "channels.discord.commands.native": "Discord Native Commands",
  "channels.discord.commands.nativeSkills": "Discord Native Skill Commands",
  "channels.discord.streaming": "Discord Streaming Mode",
  "channels.discord.streamMode": "Discord Stream Mode (Legacy)",
  "channels.discord.draftChunk.minChars": "Discord Draft Chunk Min Chars",
  "channels.discord.draftChunk.maxChars": "Discord Draft Chunk Max Chars",
  "channels.discord.draftChunk.breakPreference": "Discord Draft Chunk Break Preference",
  "channels.discord.retry.attempts": "Discord Retry Attempts",
  "channels.discord.retry.minDelayMs": "Discord Retry Min Delay (ms)",
  "channels.discord.retry.maxDelayMs": "Discord Retry Max Delay (ms)",
  "channels.discord.retry.jitter": "Discord Retry Jitter",
  "channels.discord.maxLinesPerMessage": "Discord Max Lines Per Message",
  "channels.discord.inboundWorker.runTimeoutMs": "Discord Inbound Worker Timeout (ms)",
  "channels.discord.eventQueue.listenerTimeout": "Discord EventQueue Listener Timeout (ms)",
  "channels.discord.eventQueue.maxQueueSize": "Discord EventQueue Max Queue Size",
  "channels.discord.eventQueue.maxConcurrency": "Discord EventQueue Max Concurrency",
  "channels.discord.threadBindings.enabled": "Discord Thread Binding Enabled",
  "channels.discord.threadBindings.idleHours": "Discord Thread Binding Idle Timeout (hours)",
  "channels.discord.threadBindings.maxAgeHours": "Discord Thread Binding Max Age (hours)",
  "channels.discord.threadBindings.spawnSubagentSessions": "Discord Thread-Bound Subagent Spawn",
  "channels.discord.threadBindings.spawnAcpSessions": "Discord Thread-Bound ACP Spawn",
  "channels.discord.ui.components.accentColor": "Discord Component Accent Color",
  "channels.discord.intents.presence": "Discord Presence Intent",
  "channels.discord.intents.guildMembers": "Discord Guild Members Intent",
  "channels.discord.voice.enabled": "Discord Voice Enabled",
  "channels.discord.voice.autoJoin": "Discord Voice Auto-Join",
  "channels.discord.voice.daveEncryption": "Discord Voice DAVE Encryption",
  "channels.discord.voice.decryptionFailureTolerance": "Discord Voice Decrypt Failure Tolerance",
  "channels.discord.voice.tts": "Discord Voice Text-to-Speech",
  "channels.discord.pluralkit.enabled": "Discord PluralKit Enabled",
  "channels.discord.pluralkit.token": "Discord PluralKit Token",
  "channels.discord.activity": "Discord Presence Activity",
  "channels.discord.status": "Discord Presence Status",
  "channels.discord.autoPresence.enabled": "Discord Auto Presence Enabled",
  "channels.discord.autoPresence.intervalMs": "Discord Auto Presence Check Interval (ms)",
  "channels.discord.autoPresence.minUpdateIntervalMs":
    "Discord Auto Presence Min Update Interval (ms)",
  "channels.discord.autoPresence.healthyText": "Discord Auto Presence Healthy Text",
  "channels.discord.autoPresence.degradedText": "Discord Auto Presence Degraded Text",
  "channels.discord.autoPresence.exhaustedText": "Discord Auto Presence Exhausted Text",
  "channels.discord.activityType": "Discord Presence Activity Type",
  "channels.discord.activityUrl": "Discord Presence Activity URL",
  "channels.slack.dm.policy": "Slack DM Policy",
  "channels.slack.dmPolicy": "Slack DM Policy",
  "channels.slack.configWrites": "Slack Config Writes",
  "channels.slack.commands.native": "Slack Native Commands",
  "channels.slack.commands.nativeSkills": "Slack Native Skill Commands",
  "channels.slack.allowBots": "Slack Allow Bot Messages",
  "channels.discord.allowBots": "Discord Allow Bot Messages",
  "channels.matrix.allowBots": "Matrix Allow Bot Messages",
  "channels.discord.token": "Discord Bot Token",
  "channels.slack.botToken": "Slack Bot Token",
  "channels.slack.appToken": "Slack App Token",
  "channels.slack.userToken": "Slack User Token",
  "channels.slack.userTokenReadOnly": "Slack User Token Read Only",
  "channels.slack.capabilities.interactiveReplies": "Slack Interactive Replies",
  "channels.slack.streaming": "Slack Streaming Mode",
  "channels.slack.nativeStreaming": "Slack Native Streaming",
  "channels.slack.streamMode": "Slack Stream Mode (Legacy)",
  "channels.slack.thread.historyScope": "Slack Thread History Scope",
  "channels.slack.thread.inheritParent": "Slack Thread Parent Inheritance",
  "channels.slack.thread.initialHistoryLimit": "Slack Thread Initial History Limit",
  "channels.mattermost.botToken": "Mattermost Bot Token",
  "channels.mattermost.baseUrl": "Mattermost Base URL",
  "channels.mattermost.configWrites": "Mattermost Config Writes",
  "channels.mattermost.chatmode": "Mattermost Chat Mode",
  "channels.mattermost.oncharPrefixes": "Mattermost Onchar Prefixes",
  "channels.mattermost.requireMention": "Mattermost Require Mention",
  "channels.signal.account": "Signal Account",
  "channels.imessage.cliPath": "iMessage CLI Path",
  "agents.list[].skills": "Agent Skill Filter",
  "agents.list[].identity.avatar": "Agent Avatar",
  "agents.list[].heartbeat.suppressToolErrorWarnings":
    "代理心跳抑制工具错误警告",
  "agents.list[].sandbox.browser.network": "代理沙箱浏览器网络",
  "agents.list[].sandbox.browser.cdpSourceRange": "代理沙箱浏览器 CDP 源端口范围",
  "agents.list[].sandbox.docker.dangerouslyAllowContainerNamespaceJoin":
    "Agent Sandbox Docker Allow Container Namespace Join",
  "discovery.mdns.mode": "mDNS Discovery Mode",
  plugins: "Plugins",
  "plugins.enabled": "Enable Plugins",
  "plugins.allow": "Plugin Allowlist",
  "plugins.deny": "Plugin Denylist",
  "plugins.load": "Plugin Loader",
  "plugins.load.paths": "Plugin Load Paths",
  "plugins.slots": "Plugin Slots",
  "plugins.slots.memory": "Memory Plugin",
  "plugins.slots.contextEngine": "Context Engine Plugin",
  "plugins.entries": "Plugin Entries",
  "plugins.entries.*.enabled": "Plugin Enabled",
  "plugins.entries.*.hooks": "Plugin Hook Policy",
  "plugins.entries.*.hooks.allowPromptInjection": "Allow Prompt Injection Hooks",
  "plugins.entries.*.subagent": "Plugin Subagent Policy",
  "plugins.entries.*.subagent.allowModelOverride": "Allow Plugin Subagent Model Override",
  "plugins.entries.*.subagent.allowedModels": "Plugin Subagent Allowed Models",
  "plugins.entries.*.apiKey": "Plugin API Key", // pragma: allowlist secret
  "plugins.entries.*.env": "Plugin Environment Variables",
  "plugins.entries.*.config": "Plugin Config",
  "plugins.installs": "Plugin Install Records",
  "plugins.installs.*.source": "Plugin Install Source",
  "plugins.installs.*.spec": "Plugin Install Spec",
  "plugins.installs.*.sourcePath": "Plugin Install Source Path",
  "plugins.installs.*.installPath": "Plugin Install Path",
  "plugins.installs.*.version": "Plugin Install Version",
  "plugins.installs.*.resolvedName": "Plugin Resolved Package Name",
  "plugins.installs.*.resolvedVersion": "Plugin Resolved Package Version",
  "plugins.installs.*.resolvedSpec": "Plugin Resolved Package Spec",
  "plugins.installs.*.integrity": "Plugin Resolved Integrity",
  "plugins.installs.*.shasum": "Plugin Resolved Shasum",
  "plugins.installs.*.resolvedAt": "Plugin Resolution Time",
  "plugins.installs.*.installedAt": "Plugin Install Time",
  "plugins.installs.*.marketplaceName": "Plugin Marketplace Name",
  "plugins.installs.*.marketplaceSource": "Plugin Marketplace Source",
  "plugins.installs.*.marketplacePlugin": "Plugin Marketplace Plugin",
};
